#include "Game_frame.h"

void stageBOSS (BOX ***box)
{
    int x,y;
    for(x=0;x<9;x++)
    {
        box[x][0]->state=BLOCK;
        box[x][1]->state=BLOCK;
        box[x][7]->state=BLOCK;
        box[x][8]->state=BLOCK;
    }

    for(y=0;y<9;y++)
    {
        box[0][y]->state=BOUNDARY;
        box[8][y]->state=BOUNDARY;
    }

}

void stage1 (BOX ***box)
{
    int x,y;
    for(x=0;x<9;x++)
    {
        box[x][0]->state=BOUNDARY;
        box[x][7]->state=BOUNDARY;

    }

    for(x=1;x<5;x++)
    {
        box[x][1]->state=BOUNDARY;
    }

    for(x=3;x<7;x++)
    {
        box[x][4]->state=BOUNDARY;
    }

    box[1][2]->state=BOUNDARY;
    box[1][3]->state=BOUNDARY;
    for(y=0;y<8;y++)
    {
        box[0][y]->state=BOUNDARY;
        box[8][y]->state=BOUNDARY;
    }
    box[6][3]->state=BOUNDARY;
    for(y=1;y<6;y++)
    {
        box[7][y]->state=BOUNDARY;
    }
    box[2][5]->state=BLOCK;
    box[2][6]->state=BLOCK;
    box[4][6]->state=BLOCK;
    box[5][5]->state=BLOCK;
    box[7][6]->state=EXIT;
    box[3][3]->state=MONSTER;
    box[4][2]->state=MONSTER;
    box[5][3]->state=MONSTER;
}

void stage2(BOX ***box)
{
    int x,y;
    for(x=0;x<9;x++)
    {
        box[x][0]->state=BOUNDARY;
        box[x][7]->state=BOUNDARY;
    }
    for(y=0;y<8;y++)
    {
        box[0][y]->state=BOUNDARY;
        box[8][y]->state=BOUNDARY;
    }
    box[1][1]->state=BOUNDARY;
    box[1][2]->state=BOUNDARY;
    box[1][6]->state=BOUNDARY;
    box[2][6]->state=BOUNDARY;
    for(y=2;y<7;y++)
        box[3][y]->state=BOUNDARY;
    for(y=3;y<7;y++)
        box[4][y]->state=BOUNDARY;
    box[6][1]->state=BOUNDARY;
    box[7][1]->state=BOUNDARY;
    box[2][2]->state=MONSTER;
    box[6][5]->state=MONSTER;
    box[7][6]->state=MONSTER;
    for(x=5;x<8;x++)
        box[x][3]->state=BLOCK;
    box[5][6]->state=EXIT;
    box[2][3]->element=TRAP;/**opened**/
    box[4][2]->element=TRAP;/**opened**/
    box[5][2]->element=TRAP;/**opened**/
    box[5][3]->element=TRAP;/**opened**/
    box[6][3]->element=TRAP;/**opened**/
    box[6][4]->element=TRAP;/**opened**/

    box[2][3]->damage=true;/**opened**/
    box[4][2]->damage=true;/**opened**/
    box[5][2]->damage=true;/**opened**/
    box[5][3]->damage=true;/**opened**/
    box[6][3]->damage=true;/**opened**/
    box[6][4]->damage=true;/**opened**/
}
void stage3(BOX ***box)
{
    int x,y;
    for(x=0;x<9;x++)
    {
        box[x][0]->state=BOUNDARY;
        box[x][8]->state=BOUNDARY;
    }
    for(y=0;y<9;y++)
    {
        box[0][y]->state=BOUNDARY;
        box[9][y]->state=BOUNDARY;
    }
    for(y=1;y<6;y++)
    {
        box[1][y]->state=BOUNDARY;
        box[2][y]->state=BOUNDARY;
    }
    box[2][6]->state=BOUNDARY;
    box[3][1]->state=BOUNDARY;
    for(x=0;x<7;x++)
        box[x][2]->state=BOUNDARY;
    box[8][1]->state=BOUNDARY;
    box[8][2]->state=BOUNDARY;
    box[8][5]->state=BOUNDARY;
    box[8][6]->state=BOUNDARY;
    box[8][7]->state=BOUNDARY;
    box[4][4]->state=BOUNDARY;
    box[4][6]->state=BOUNDARY;
    box[6][4]->state=BOUNDARY;
    box[6][6]->state=BOUNDARY;
    box[3][4]->element=TRAP;/**opened**/
    box[4][3]->element=TRAP;/**opened**/
    box[5][3]->element=TRAP;/**opened**/
    box[5][4]->element=TRAP;/**opened**/
    box[3][6]->element=TRAP;/**opened**/
    box[5][6]->element=TRAP;/**opened**/
    box[6][5]->element=TRAP;/**opened**/
    box[7][5]->element=TRAP;/**opened**/
    box[5][5]->state=MONSTER;
    box[6][7]->state=MONSTER;
    box[7][2]->state=DOOR;
    box[1][6]->element=KEY;
    box[4][1]->state=EXIT;

    box[3][4]->damage=true;/**opened**/
    box[4][3]->damage=true;/**opened**/
    box[5][3]->damage=true;/**opened**/
    box[5][4]->damage=true;/**opened**/
    box[3][6]->damage=true;/**opened**/
    box[5][6]->damage=true;/**opened**/
    box[6][5]->damage=true;/**opened**/
    box[7][5]->damage=true;/**opened**/
}
void stage4(BOX ***box)
{
    int x,y;
    for(x=0;x<10;x++)
    {
        box[x][0]->state=BOUNDARY;
        box[x][6]->state=BOUNDARY;
    }
    for(y=0;y<7;y++)
    {
        box[0][y]->state=BOUNDARY;
        box[9][y]->state=BOUNDARY;
    }
    box[2][1]->state=BOUNDARY;
    box[6][1]->state=BOUNDARY;
    box[7][1]->state=BOUNDARY;
    box[8][1]->state=BOUNDARY;
    box[8][2]->state=BOUNDARY;
    box[1][5]->state=BOUNDARY;
    box[7][5]->state=BOUNDARY;
    box[8][5]->state=BOUNDARY;
    box[5][1]->state=BLOCK;
    box[3][3]->state=BLOCK;
    box[5][5]->state=BLOCK;
    box[4][4]->state=BLOCK;
    box[2][4]->state=BLOCK;
    box[3][5]->state=BLOCK;
    box[2][2]->state=BLOCK;
    box[4][2]->state=BLOCK;
    box[1][3]->state=BLOCK;
    box[5][3]->state=BLOCK;
    box[6][3]->state=BLOCK;
    box[6][4]->state=BLOCK;
    box[7][4]->state=BLOCK;
    box[3][2]->element=TRAP;/**opened**/
    box[4][2]->element=TRAP;/**opened**/
    box[3][1]->element=KEY;
    box[6][2]->state=DOOR;
    box[8][3]->state=EXIT;
}

void stage5(BOX ***box) //Breathing trap.
{
    int x,y;
    for(x=0;x<8;x++)
    {
        box[x][0]->state=BOUNDARY;
        box[x][8]->state=BOUNDARY;
    }
    for(y=0;y<9;y++)
    {
        box[0][y]->state=BOUNDARY;
        box[7][y]->state=BOUNDARY;
    }
    box[1][1]->state=BOUNDARY;
    box[1][2]->state=BOUNDARY;
    for(y=1;y<6;y++)
    {
        box[2][y]->state=BOUNDARY;
    }
    for(x=1;x<6;x++)
    {
        box[x][7]->state=BOUNDARY;
    }
    box[6][7]->element=KEY;
    box[3][1]->state=BOUNDARY;
    box[6][1]->state=BOUNDARY;
    box[1][5]->state=MONSTER;
    for(x=3;x<7;x++)
    {
    box[x][5]->state=BLOCK;
    }
    box[5][2]->state=BLOCK;
    box[5][3]->state=BLOCK;
    box[4][2]->state=DOOR;
    box[1][6]->element=FlexibleTrap;/**closed**/
    box[3][6]->element=FlexibleTrap;/**closed**/
    box[6][6]->element=FlexibleTrap;/**closed**/
    box[6][4]->element=FlexibleTrap;/**closed**/
    box[4][4]->element=FlexibleTrap;/**closed**/
    box[3][3]->element=FlexibleTrap;/**closed**/
    box[5][1]->state=EXIT;

    box[1][6]->damage=false;/**closed**/
    box[3][6]->damage=false;/**closed**/
    box[6][6]->damage=false;/**closed**/
    box[6][4]->damage=false;/**closed**/
    box[4][4]->damage=false;/**closed**/
    box[3][3]->damage=false;/**closed**/
}

void stage6(BOX ***box) //Breathing trap.
{
    int x,y;
    for(x=0;x<9;x++)
    {
        box[x][0]->state=BOUNDARY;
        box[x][9]->state=BOUNDARY;
    }
    for(y=0;y<10;y++)
    {
        box[0][y]->state=BOUNDARY;
        box[1][y]->state=BOUNDARY;
        box[8][y]->state=BOUNDARY;
    }
    box[1][3]->state=EMPTY;
    for(x=5;x<8;x++)
        for(y=1;y<4;y++)
        box[x][y]->state=BOUNDARY;
    for(x=2;x<5;x++)
        for(y=7;y<10;y++)
        box[x][y]->state=BOUNDARY;
    box[6][4]->state=BOUNDARY;
    box[7][4]->state=BOUNDARY;
    box[7][6]->state=BOUNDARY;
    box[7][8]->state=BOUNDARY;
    box[3][5]->state=BOUNDARY;
    for(x=2;x<5;x++)
        box[x][2]->state=BLOCK;
    box[3][4]->state=BLOCK;
    box[4][5]->state=BLOCK;
    box[4][6]->state=BLOCK;
    box[5][5]->state=BLOCK;
    box[6][7]->state=BLOCK;
    box[2][5]->state=MONSTER;
    box[6][6]->state=MONSTER;
    box[4][3]->element=KEY;
    box[5][7]->state=DOOR;
    box[6][8]->state=EXIT;
    box[2][4]->element=FlexibleTrap;/**closed**/
    box[3][4]->element=FlexibleTrap;/**closed**/

    box[2][4]->damage=false;/**closed**/
    box[3][4]->damage=false;/**closed**/
}

void stage7(BOX ***box) //Breathing trap.
{
    int x,y;
    for(x=0;x<8;x++)
    {
        box[x][0]->state=BOUNDARY;
        box[x][8]->state=BOUNDARY;
    }
    for(y=0;y<9;y++)
    {
        box[0][y]->state=BOUNDARY;
        box[7][y]->state=BOUNDARY;
    }
    for(x=1;x<4;x++)
        for(y=1;y<3;y++)
        box[x][y]->state=BOUNDARY;
    box[3][3]->state=BOUNDARY;
    box[6][1]->state=BOUNDARY;
    box[5][7]->state=BOUNDARY;
    box[5][6]->state=BOUNDARY;
    box[6][7]->state=BOUNDARY;
    box[6][6]->state=BOUNDARY;
    box[2][5]->state=BOUNDARY;
    box[2][6]->state=BOUNDARY;
    box[3][6]->state=BOUNDARY;
    box[4][3]->state=BLOCK;
    box[2][4]->state=BLOCK;
    box[5][3]->state=BLOCK;
    box[5][4]->state=BLOCK;
    box[6][3]->state=BLOCK;
    box[4][4]->state=MONSTER;
    box[1][4]->state=MONSTER;
    box[3][5]->state=MONSTER;
    box[2][3]->element=KEY;
    box[4][1]->state=EXIT;
    box[5][2]->state=DOOR;
    box[1][6]->element=FlexibleTrap;/**opened**/
    box[2][7]->element=FlexibleTrap;/**opened**/
    box[4][7]->element=FlexibleTrap;/**opened**/
    box[1][7]->element=FlexibleTrap;/**closed**/
    box[3][7]->element=FlexibleTrap;/**closed**/
    box[4][6]->element=FlexibleTrap;/**closed**/

    box[1][6]->damage=true;
    box[2][7]->damage=true;
    box[4][7]->damage=true;
    box[1][7]->damage=false;
    box[3][7]->damage=false;
    box[4][6]->damage=false;
}

void stage9(BOX ***box)
{
    int x,y;
    for(x=0;x<11;x++)
    {
        box[x][0]->state=BOUNDARY;
        box[x][1]->state=BOUNDARY;
        box[x][8]->state=BOUNDARY;
    }
    for(y=0;y<9;y++)
    {
        box[0][y]->state=BOUNDARY;
        box[10][y]->state=BOUNDARY;
    }
    box[1][1]->state=BOUNDARY;
    box[1][2]->state=BOUNDARY;
    box[1][3]->state=BOUNDARY;
    box[1][4]->state=BOUNDARY;
    box[2][1]->state=BOUNDARY;
    box[2][2]->state=BOUNDARY;
    box[2][3]->state=BOUNDARY;
    box[3][1]->state=BOUNDARY;
    box[3][2]->state=BOUNDARY;
    box[3][3]->state=BOUNDARY;
    box[3][4]->state=BOUNDARY;
    box[7][1]->state=BOUNDARY;
    box[7][2]->state=BOUNDARY;
    box[7][3]->state=BOUNDARY;
    box[7][4]->state=BOUNDARY;
    box[8][1]->state=BOUNDARY;
    box[8][2]->state=BOUNDARY;
    box[8][3]->state=BOUNDARY;
    box[9][1]->state=BOUNDARY;
    box[9][2]->state=BOUNDARY;
    box[9][3]->state=BOUNDARY;
    box[9][4]->state=BOUNDARY;
    box[1][7]->state=BOUNDARY;
    box[9][7]->state=BOUNDARY;
    for(y=3;y<8;y++)
        box[4][y]->state=BLOCK;
    box[1][5]->state=BLOCK;
    box[2][4]->state=BLOCK;
    box[2][6]->state=BLOCK;
    box[3][6]->state=BLOCK;
    box[4][5]->state=BLOCK;
    box[5][5]->state=BLOCK;
    box[6][5]->state=BLOCK;
    box[6][3]->state=BLOCK;
    box[7][6]->state=BLOCK;
    box[7][7]->state=BLOCK;
    box[8][6]->state=BLOCK;
    box[9][5]->element=KEY;
    box[5][3]->state=DOOR;
    box[5][1]->state=EXIT;
}
