//void load1Attack(STAGE *stage)
//{
//
//stage->attack=calloc(1,sizeof(AttackModule));
//AttackModule *now=stage->attack;
//
//
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=8;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=11;
//now->type=VERTIC;
//now=now->next;
//
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=14;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=17;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=20;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=23;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=26;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=29;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=32;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=35;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=38;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=41;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=44;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=47;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=47;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=50;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=50;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=53;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=53;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=56;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=59;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=62;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=65;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=65;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=68;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=68;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=71;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=71;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=74;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=74;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=74;
//now->type=VERTIC;
//now=now->next;
//
//}




//void load2Attack(STAGE *stage)//-----------------------------------------------------------------------------
//{
//
//stage->attack=calloc(1,sizeof(AttackModule));
//AttackModule *now=stage->attack;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=8;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=8;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=8;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=11;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=11;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=14;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=17;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=17;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=20;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=20;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=20;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=0;
//now->step=23;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=8;
//now->x=0;
//now->step=26;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=0;
//now->step=29;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=7;
//now->x=0;
//now->step=29;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=1;
//now->x=0;
//now->step=32;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=0;
//now->step=35;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=38;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=38;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=41;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=41;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=41;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=41;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=44;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=47;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=47;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=47;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=50;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=50;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=50;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=50;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=53;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=53;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=53;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=56;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=56;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=59;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=59;
//now->type=VERTIC;
//now=now->next;
//
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=62;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=62;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=62;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=65;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=65;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=68;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=68;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=68;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=68;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=68;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=71;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=71;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=74;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=74;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=74;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=77;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=77;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=77;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=80;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=80;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=83;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=83;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=86;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=86;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=89;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=89;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=92;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=92;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=95;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=95;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=98;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=98;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=101;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=101;
//now->type=VERTIC;
//now=now->next;
//}




//void load3Attack(STAGE *stage)//-----------------------------------------------------------------------------
//{
//
//stage->attack=calloc(1,sizeof(AttackModule));
//AttackModule *now=stage->attack;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=8;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=11;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=11;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=14;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=14;
//now->type=VERTIC;
//now=now->next;
//
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=17;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=17;
//now->type=VERTIC;
//now=now->next;
//
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=8;
//now->x=0;
//now->step=20;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=7;
//now->x=0;
//now->step=23;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=26;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=26;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=7;
//now->x=0;
//now->step=29;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=32;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=32;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=0;
//now->step=35;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=38;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=38;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=0;
//now->step=41;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=44;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=50;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=50;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=50;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=53;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=53;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=53;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=53;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=0;
//now->step=56;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=59;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=59;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=62;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=0;
//now->step=62;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=0;
//now->step=62;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=65;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=65;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=68;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=68;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=0;
//now->step=68;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=71;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=71;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=74;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=7;
//now->x=0;
//now->step=74;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=77;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=77;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=77;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=80;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=80;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=80;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=80;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=80;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=83;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=83;
//now->type=VERTIC;
//now=now->next;
////--------------------------------------------
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=86;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=86;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=86;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=86;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=89;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=89;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=0;
//now->step=89;
//now->type=HORIZON;
//now=now->next;
//
//
//}

//void load4Attack(STAGE *stage)//-----------------------------------------------------------------------------
//{
//
//stage->attack=calloc(1,sizeof(AttackModule));
//AttackModule *now=stage->attack;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=8;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=0;
//now->step=8;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=0;
//now->step=11;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=0;
//now->step=11;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=11;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=11;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=0;
//now->step=14;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=6;
//now->x=0;
//now->step=14;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=14;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=14;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=0;
//now->step=17;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=17;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=17;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=7;
//now->x=0;
//now->step=20;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=20;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=20;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=6;
//now->x=0;
//now->step=23;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=23;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=23;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=0;
//now->step=26;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=26;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=26;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=29;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=29;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=32;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=32;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=35;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=35;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=38;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=41;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=41;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=44;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=44;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=47;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=47;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=50;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=50;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=53;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=53;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=56;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=56;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=59;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=62;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=62;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=0;
//now->step=62;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=0;
//now->step=62;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=65;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=65;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=0;
//now->step=65;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=0;
//now->step=65;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=68;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=0;
//now->step=68;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=71;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=71;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=0;
//now->step=71;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=7;
//now->x=0;
//now->step=71;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=74;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=5;
//now->x=0;
//now->step=74;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=7;
//now->x=0;
//now->step=74;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=3;
//now->step=77;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=4;
//now->step=77;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=5;
//now->step=77;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=1;
//now->x=0;
//now->step=80;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=6;
//now->x=0;
//now->step=80;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=80;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=80;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=1;
//now->step=83;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=2;
//now->step=83;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=6;
//now->step=83;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=7;
//now->step=83;
//now->type=VERTIC;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=0;
//now->x=0;
//now->step=83;
//now->type=HORIZON;
//now=now->next;
//}

//void load5Attack(STAGE *stage)//------------------------------------------------------------------------------------------------
//{
//
//stage->attack=calloc(1,sizeof(AttackModule));
//AttackModule *now=stage->attack;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=1;
//now->x=2;
//now->dx=6;
//now->step=8;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=2;
//now->dx=6;
//now->step=10;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=2;
//now->dx=6;
//now->step=12;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=1;
//now->x=1;
//now->dx=4;
//now->step=12;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=2;
//now->dx=6;
//now->step=14;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=1;
//now->dx=4;
//now->step=14;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=1;
//now->dx=4;
//now->step=16;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=1;
//now->x=5;
//now->dx=4;
//now->step=18;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=1;
//now->dx=4;
//now->step=18;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=5;
//now->dx=4;
//now->step=20;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=5;
//now->dx=4;
//now->step=22;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=1;
//now->x=2;
//now->dx=6;
//now->step=24;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=5;
//now->dx=4;
//now->step=24;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=2;
//now->dx=6;
//now->step=26;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=2;
//now->dx=6;
//now->step=28;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=2;
//now->dx=6;
//now->step=30;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=1;
//now->x=0;
//now->step=28;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=0;
//now->step=29;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=2;
//now->step=30;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=1;
//now->step=31;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=4;
//now->step=32;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=3;
//now->step=33;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));//大激光(2,1)(8,4)
//now->x=2;
//now->y=1;
//now->dx=6;
//now->dy=3;
//now->step=37;
//now->type=AREA;
//now=now->next;//first stage end
//
//}

//void loa6Attack(STAGE *stage)//---------------------------------------------------------------------------------------------------------------
//{
//
//stage->attack=calloc(1,sizeof(AttackModule));
//AttackModule *now=stage->attack;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=1;
//now->x=2;
//now->dx=6;
//now->step=8;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=2;
//now->dx=6;
//now->step=10;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=2;
//now->dx=6;
//now->step=12;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=1;
//now->x=5;
//now->dx=4;
//now->step=12;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=2;
//now->dx=6;
//now->step=14;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=5;
//now->dx=4;
//now->step=14;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=5;
//now->dx=4;
//now->step=16;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=1;
//now->x=1;
//now->dx=4;
//now->step=18;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=5;
//now->dx=4;
//now->step=18;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=1;
//now->dx=4;
//now->step=20;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=1;
//now->dx=4;
//now->step=22;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=1;
//now->x=2;
//now->dx=6;
//now->step=24;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=1;
//now->dx=4;
//now->step=24;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=2;
//now->dx=6;
//now->step=26;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=2;
//now->dx=6;
//now->step=28;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=4;
//now->x=2;
//now->dx=6;
//now->step=30;
//now->type=LINE;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=2;
//now->x=0;
//now->step=26;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->y=3;
//now->x=0;
//now->step=26;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=1;
//now->step=27;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=4;
//now->step=27;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=3;
//now->step=28;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=4;
//now->step=28;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=2;
//now->step=29;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=3;
//now->step=29;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=1;
//now->step=30;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=4;
//now->step=30;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=1;
//now->step=31;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=2;
//now->step=31;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=3;
//now->step=32;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=0;
//now->y=4;
//now->step=32;
//now->type=HORIZON;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=1;
//now->y=1;
//now->dx=1;
//now->dy=1;
//now->step=36;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=1;
//now->y=3;
//now->dx=1;
//now->dy=1;
//now->step=36;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=4;
//now->y=1;
//now->dx=1;
//now->dy=1;
//now->step=36;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=4;
//now->y=3;
//now->dx=1;
//now->dy=1;
//now->step=36;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=7;
//now->y=1;
//now->dx=1;
//now->dy=1;
//now->step=36;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=7;
//now->y=3;
//now->dx=1;
//now->dy=1;
//now->step=36;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=7;
//now->y=1;
//now->dx=1;
//now->dy=1;
//now->step=38;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=2;
//now->y=3;
//now->dx=7;
//now->dy=1;
//now->step=38;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=2;
//now->y=1;
//now->dx=1;
//now->dy=1;
//now->step=40;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=2;
//now->y=3;
//now->dx=1;
//now->dy=1;
//now->step=40;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=5;
//now->y=1;
//now->dx=1;
//now->dy=1;
//now->step=40;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=5;
//now->y=3;
//now->dx=1;
//now->dy=1;
//now->step=40;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=8;
//now->y=1;
//now->dx=1;
//now->dy=1;
//now->step=40;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=8;
//now->y=3;
//now->dx=1;
//now->dy=1;
//now->step=40;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=1;
//now->y=1;
//now->dx=7;
//now->dy=1;
//now->step=42;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=3;
//now->y=3;
//now->dx=1;
//now->dy=1;
//now->step=42;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=2;
//now->y=1;
//now->dx=1;
//now->dy=1;
//now->step=44;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=5;
//now->y=1;
//now->dx=1;
//now->dy=1;
//now->step=44;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=8;
//now->y=1;
//now->dx=1;
//now->dy=1;
//now->step=44;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=1;
//now->y=3;
//now->dx=1;
//now->dy=1;
//now->step=44;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=4;
//now->y=3;
//now->dx=1;
//now->dy=1;
//now->step=44;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=7;
//now->y=3;
//now->dx=1;
//now->dy=1;
//now->step=44;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=1;
//now->y=1;
//now->dx=1;
//now->dy=1;
//now->step=46;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=4;
//now->y=1;
//now->dx=1;
//now->dy=1;
//now->step=46;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=7;
//now->y=1;
//now->dx=1;
//now->dy=1;
//now->step=46;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=2;
//now->y=3;
//now->dx=1;
//now->dy=1;
//now->step=46;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=5;
//now->y=3;
//now->dx=1;
//now->dy=1;
//now->step=46;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=8;
//now->y=3;
//now->dx=1;
//now->dy=1;
//now->step=46;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=1;
//now->y=1;
//now->dx=1;
//now->dy=3;
//now->step=48;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=8;
//now->y=1;
//now->dx=1;
//now->dy=3;
//now->step=48;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=1;
//now->y=1;
//now->dx=3;
//now->dy=3;
//now->step=50;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));
//now->x=6;
//now->y=1;
//now->dx=3;
//now->dy=3;
//now->step=50;
//now->type=AREA;
//now=now->next;
//
//now->next=calloc(1,sizeof(AttackModule));//大激光(2,1)(8,4)
//now->x=2;
//now->y=1;
//now->dx=6;
//now->dy=3;
//now->step=50;
//now->type=AREA;
//now=now->next;//second stage end
//
//}
